/*
 *  Copyright (C) 2005-2021 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

/* File autogenerated, see xbmc/addons/kodi-dev-kit/tools/code-generator/code_generator.py */

#include "context_menu.h"

// Shared API
#include "addons/kodi-dev-kit/src/shared/api/gui/dialogs/context_menu.h"

// Kodi
#include "addons/interface/RunningProcess.h"
#include "utils/log.h"

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1>---*/

#include "dialogs/GUIDialogContextMenu.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIWindowManager.h"

/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1_END>---*/

namespace KODI
{
namespace ADDONS
{
namespace INTERFACE
{

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2_END>---*/

void CHdl_kodi_gui_dialogs_context_menu_h::InitDirect(
    directFuncToKodi_gui_dialogs_context_menu_h* ifcToKodi,
    directFuncToAddon_gui_dialogs_context_menu_h* ifcToAddon)
{
  ifcToKodi->thisClassHdl = this;
  m_ifcToAddon = ifcToAddon;
  ifcToKodi->kodi_gui_dialogs_context_menu_open_v1 = kodi_gui_dialogs_context_menu_open_v1;
}

bool CHdl_kodi_gui_dialogs_context_menu_h::HandleMessage(int funcGroup,
                                                         int func,
                                                         const msgpack::unpacked& in,
                                                         msgpack::sbuffer& out)
{
  if (funcGroup != funcGroup_gui_dialogs_context_menu_h)
    return false;

  switch (func)
  {
    case funcParent_kodi_gui_dialogs_context_menu_open_v1:
    {
      // Original API call: ATTR_DLL_EXPORT int kodi_gui_dialogs_context_menu_open(const char* heading, const char* entries[], size_t size) __INTRODUCED_IN_KODI(1);
      // Tuple in:          typedef std::tuple<std::string, std::vector<std::string>, size_t> msgParent__IN_kodi_gui_dialogs_context_menu_open_v1; /* Autogenerated */
      // Tuple out:         typedef std::tuple<int> msgParent_OUT_kodi_gui_dialogs_context_menu_open_v1; /* Autogenerated */
      msgParent__IN_kodi_gui_dialogs_context_menu_open_v1 t = in.get().as<decltype(t)>();
      const std::string& heading = std::get<0>(t);
      const std::vector<std::string>& cpp_entries = std::get<1>(t);
      size_t size = std::get<2>(t);

      std::vector<const char*> entries;
      entries.reserve(size);
      for (size_t i = 0; i < size; ++i)
      {
        entries.emplace_back(cpp_entries[i].c_str());
      }
      assert(cpp_entries.size() == size);

      int auto_gen_ret =
          kodi_gui_dialogs_context_menu_open_v1(this, heading.c_str(), entries.data(), size);
      msgpack::pack(out, msgParent_OUT_kodi_gui_dialogs_context_menu_open_v1(auto_gen_ret));
      return true;
    }
    default:
      CLog::Log(LOGERROR,
                "CHdl_kodi_gui_dialogs_context_menu_h::{}: addon called with unknown function id "
                "'{}' on group 'gui_dialogs_context_menu_h'",
                __func__, func);
  }

  return false;
}

// Function calls from Kodi to addon
/* NOTE: unused (no functions here) */

// Callbacks from addon to Kodi

int CHdl_kodi_gui_dialogs_context_menu_h::kodi_gui_dialogs_context_menu_open_v1(
    void* thisClassHdl, const char* heading, const char* entries[], size_t size)
{
  auto thisClass = reinterpret_cast<CHdl_kodi_gui_dialogs_context_menu_h*>(thisClassHdl);
  if (thisClass == nullptr)
    return -1;

  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_KODI_GUI_DIALOGS_CONTEXT_MENU_OPEN>---*/
  // Code below must be set manually by hand to make work to Kodi

  CGUIDialogContextMenu* dialog =
      CServiceBroker::GetGUI()->GetWindowManager().GetWindow<CGUIDialogContextMenu>(
          WINDOW_DIALOG_CONTEXT_MENU);

  CContextButtons choices;
  for (unsigned int i = 0; i < size; ++i)
    choices.Add(i, entries[i]);

  return dialog->Show(choices);

  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_KODI_GUI_DIALOGS_CONTEXT_MENU_OPEN_END>---*/
}

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_3>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_3_END>---*/

} /* namespace INTERFACE */
} /* namespace ADDONS */
} /* namespace KODI */
