/*
 *  Copyright (C) 2005-2021 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

/* File autogenerated, see xbmc/addons/kodi-dev-kit/tools/code-generator/code_generator.py */

#include "text_viewer.h"

// Shared API
#include "addons/kodi-dev-kit/src/shared/api/gui/dialogs/text_viewer.h"

// Kodi
#include "addons/interface/RunningProcess.h"
#include "utils/log.h"

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1>---*/
#include "dialogs/GUIDialogTextViewer.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIWindowManager.h"
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1_END>---*/

namespace KODI
{
namespace ADDONS
{
namespace INTERFACE
{

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2_END>---*/

void CHdl_kodi_gui_dialogs_text_viewer_h::InitDirect(
    directFuncToKodi_gui_dialogs_text_viewer_h* ifcToKodi,
    directFuncToAddon_gui_dialogs_text_viewer_h* ifcToAddon)
{
  ifcToKodi->thisClassHdl = this;
  m_ifcToAddon = ifcToAddon;
  ifcToKodi->kodi_gui_dialogs_text_viewer_show_v1 = kodi_gui_dialogs_text_viewer_show_v1;
}

bool CHdl_kodi_gui_dialogs_text_viewer_h::HandleMessage(int funcGroup,
                                                        int func,
                                                        const msgpack::unpacked& in,
                                                        msgpack::sbuffer& out)
{
  if (funcGroup != funcGroup_gui_dialogs_text_viewer_h)
    return false;

  switch (func)
  {
    case funcParent_kodi_gui_dialogs_text_viewer_show_v1:
    {
      // Original API call: ATTR_DLL_EXPORT void kodi_gui_dialogs_text_viewer_show(const char* heading, const char* text) __INTRODUCED_IN_KODI(1);
      // Tuple in:          typedef std::tuple<std::string, std::string> msgParent__IN_kodi_gui_dialogs_text_viewer_show_v1; /* Autogenerated */
      // Tuple out:         typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_dialogs_text_viewer_show_v1; /* Autogenerated */
      msgParent__IN_kodi_gui_dialogs_text_viewer_show_v1 t = in.get().as<decltype(t)>();
      const std::string& heading = std::get<0>(t);
      const std::string& text = std::get<1>(t);
      kodi_gui_dialogs_text_viewer_show_v1(this, heading.c_str(), text.c_str());
      return true;
    }
    default:
      CLog::Log(LOGERROR,
                "CHdl_kodi_gui_dialogs_text_viewer_h::{}: addon called with unknown function id "
                "'{}' on group 'gui_dialogs_text_viewer_h'",
                __func__, func);
  }

  return false;
}

// Function calls from Kodi to addon
/* NOTE: unused (no functions here) */

// Callbacks from addon to Kodi

void CHdl_kodi_gui_dialogs_text_viewer_h::kodi_gui_dialogs_text_viewer_show_v1(void* thisClassHdl,
                                                                               const char* heading,
                                                                               const char* text)
{
  auto thisClass = reinterpret_cast<CHdl_kodi_gui_dialogs_text_viewer_h*>(thisClassHdl);
  if (thisClass == nullptr)
    return;

  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_KODI_GUI_DIALOGS_TEXT_VIEWER_SHOW>---*/

  CGUIDialogTextViewer* dialog =
      CServiceBroker::GetGUI()->GetWindowManager().GetWindow<CGUIDialogTextViewer>(
          WINDOW_DIALOG_TEXT_VIEWER);
  if (!heading || !text || !dialog)
  {
    CLog::Log(
        LOGERROR,
        "CHdl_kodi_gui_dialogs_text_viewer_h::{} - invalid handler data (heading='{}', text='{}', "
        "dialog='{}') on addon '{}'",
        __func__, static_cast<const void*>(heading), static_cast<const void*>(text),
        static_cast<void*>(dialog), thisClass->m_process->GetAddonID());
    return;
  }

  dialog->SetHeading(heading);
  dialog->SetText(text);
  dialog->Open();

  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_KODI_GUI_DIALOGS_TEXT_VIEWER_SHOW_END>---*/
}

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_3>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_3_END>---*/

} /* namespace INTERFACE */
} /* namespace ADDONS */
} /* namespace KODI */
