/*
 *  Copyright (C) 2005-2021 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

/* File autogenerated, see xbmc/addons/kodi-dev-kit/tools/code-generator/code_generator.py */

#pragma once

#include "../../../../include/kodi/c-api/addon-instance/videocodec.h"
#include "src/shared/SharedGroups.h"

#include <string.h>
#include <string>
#include <tuple>
#include <vector>

/* API struct from 1 to 1 */
typedef struct KODI_ADDON_VIDEOCODEC_FUNC_V1_TO_V1
{
  PFN_KODI_ADDON_VIDEOCODEC_CREATE_V1 create; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_VIDEOCODEC_DESTROY_V1 destroy; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_VIDEOCODEC_OPEN_V1 open; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_VIDEOCODEC_RECONFIGURE_V1 reconfigure; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_VIDEOCODEC_ADD_DATA_V1 add_data; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_VIDEOCODEC_GET_PICTURE_V1 get_picture; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_VIDEOCODEC_GET_NAME_V1 get_name; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_VIDEOCODEC_RESET_V1 reset; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
} KODI_ADDON_VIDEOCODEC_FUNC_V1_TO_V1;

union KODI_ADDON_VIDEOCODEC_FUNC_UNION
{
  struct KODI_ADDON_VIDEOCODEC_FUNC_V1_TO_V1 v1;
};

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1_END>---*/

namespace KODI
{
namespace ADDONS
{
namespace INTERFACE
{

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2_END>---*/

// Code here relates to direct API calls without use of shared mem from addon to Kodi.
//{{{

typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_VIDEOCODEC_GET_FRAME_BUFFER_V1)(
    void*, KODI_OWN_HDL, struct VIDEOCODEC_PICTURE*);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_VIDEOCODEC_RELEASE_FRAME_BUFFER_V1)(
    void*, KODI_OWN_HDL, struct VIDEOCODEC_PICTURE*);

struct directFuncToKodi_addoninstance_videocodec_h
{
  void* thisClassHdl;
  PFN_INT_KODI_ADDON_VIDEOCODEC_GET_FRAME_BUFFER_V1 kodi_addon_videocodec_get_frame_buffer_v1;
  PFN_INT_KODI_ADDON_VIDEOCODEC_RELEASE_FRAME_BUFFER_V1
      kodi_addon_videocodec_release_frame_buffer_v1;
};

//}}}

// Code here relates to direct API calls without use of shared mem from Kodi to addon.
//{{{

typedef KODI_ADDON_VIDEOCODEC_HDL(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_VIDEOCODEC_CREATE_V1)(
    void*, KODI_OWN_HDL);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_VIDEOCODEC_ADD_DATA_V1)(
    void*, KODI_ADDON_VIDEOCODEC_HDL, const struct DEMUX_PACKET*);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_VIDEOCODEC_OPEN_V1)(void*,
                                                                       KODI_ADDON_VIDEOCODEC_HDL,
                                                                       struct VIDEOCODEC_INITDATA*);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_VIDEOCODEC_RECONFIGURE_V1)(
    void*, KODI_ADDON_VIDEOCODEC_HDL, struct VIDEOCODEC_INITDATA*);
typedef const char*(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_VIDEOCODEC_GET_NAME_V1)(
    void*, KODI_ADDON_VIDEOCODEC_HDL);
typedef enum VIDEOCODEC_RETVAL(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_VIDEOCODEC_GET_PICTURE_V1)(
    void*, KODI_ADDON_VIDEOCODEC_HDL, struct VIDEOCODEC_PICTURE*);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_VIDEOCODEC_DESTROY_V1)(
    void*, KODI_ADDON_VIDEOCODEC_HDL);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_VIDEOCODEC_RESET_V1)(void*,
                                                                        KODI_ADDON_VIDEOCODEC_HDL);

struct directFuncToAddon_addoninstance_videocodec_h
{
  void* thisClassHdl;
  PFN_INT_KODI_ADDON_VIDEOCODEC_ADD_DATA_V1 kodi_addon_videocodec_add_data_v1;
  PFN_INT_KODI_ADDON_VIDEOCODEC_CREATE_V1 kodi_addon_videocodec_create_v1;
  PFN_INT_KODI_ADDON_VIDEOCODEC_DESTROY_V1 kodi_addon_videocodec_destroy_v1;
  PFN_INT_KODI_ADDON_VIDEOCODEC_GET_NAME_V1 kodi_addon_videocodec_get_name_v1;
  PFN_INT_KODI_ADDON_VIDEOCODEC_GET_PICTURE_V1 kodi_addon_videocodec_get_picture_v1;
  PFN_INT_KODI_ADDON_VIDEOCODEC_OPEN_V1 kodi_addon_videocodec_open_v1;
  PFN_INT_KODI_ADDON_VIDEOCODEC_RECONFIGURE_V1 kodi_addon_videocodec_reconfigure_v1;
  PFN_INT_KODI_ADDON_VIDEOCODEC_RESET_V1 kodi_addon_videocodec_reset_v1;
};

//}}}

typedef enum funcParent_addoninstance_videocodec_h : int
{
  funcParent_addoninstance_videocodec_h_dummy
} funcParent_addoninstance_videocodec_h;

// clang-format off
/*---AUTO_GEN_PARSE<FUNC_PARENT_TUPLES>---*/
/* NOTE: Ignored as direct api only is set! */
/*---AUTO_GEN_PARSE<FUNC_PARENT_TUPLES_END>---*/
// clang-format on

//==============================================================================

typedef enum funcChild_addoninstance_videocodec_h : int
{
  funcChild_addoninstance_videocodec_h_dummy
} funcChild_addoninstance_videocodec_h;

// clang-format off
/*---AUTO_GEN_PARSE<FUNC_CHILD_TUPLES>---*/
/* NOTE: Ignored as direct api only is set! */
/*---AUTO_GEN_PARSE<FUNC_CHILD_TUPLES_END>---*/
// clang-format on

} /* namespace INTERFACE */
} /* namespace ADDONS */
} /* namespace KODI */
