/*
 *  Copyright (C) 2005-2021 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

/* File autogenerated, see xbmc/addons/kodi-dev-kit/tools/code-generator/code_generator.py */

#include "monitor.h"

// Shared API
#include "src/shared/Instances.h"

// Lib code
#include "core/addon_control.h"

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1_END>---*/

using namespace KODI::ADDONS::INTERFACE;
using namespace KODI_ADDON::INTERNAL;

namespace KODI_ADDON
{
namespace INTERNAL
{

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2_END>---*/

void CHdl_kodi_monitor_h::InitDirect(directFuncToAddon_monitor_h* ifcToAddon)
{
  ifcToAddon->thisClassHdl = this;
}

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_3>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_3_END>---*/

/* NOTE: unused (no functions from Kodi to addon here) */

} /* namespace INTERNAL */
} /* namespace KODI_ADDON */

ATTR_DLL_EXPORT bool kodi_monitor_wait_for_abort(double timeout)
{
  // Original API call: ATTR_DLL_EXPORT bool kodi_monitor_wait_for_abort(double timeout) __INTRODUCED_IN_KODI(1);
  // Tuple in:          /* NOTE: msgParent__IN_kodi_monitor_wait_for_abort - Override active to use inside dev-kit library only */
  // Tuple out:         /* NOTE: msgParent_OUT_kodi_monitor_wait_for_abort - Override active to use inside dev-kit library only */

  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_KODI_MONITOR_WAIT_FOR_ABORT_V1>---*/

  std::mutex mtx;
  std::unique_lock<std::mutex> lck(mtx);
  AddonIfc::g_ifc->m_cv.wait_for(lck, std::chrono::duration<double>(timeout));
  return AddonIfc::g_ifc->killCalled;

  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_KODI_MONITOR_WAIT_FOR_ABORT_V1_END>---*/
}

ATTR_DLL_EXPORT bool kodi_monitor_abort_requested()
{
  // Original API call: ATTR_DLL_EXPORT bool kodi_monitor_abort_requested() __INTRODUCED_IN_KODI(1);
  // Tuple in:          /* NOTE: msgParent__IN_kodi_monitor_abort_requested - Override active to use inside dev-kit library only */
  // Tuple out:         /* NOTE: msgParent_OUT_kodi_monitor_abort_requested - Override active to use inside dev-kit library only */

  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_KODI_MONITOR_ABORT_REQUESTED_V1>---*/

  return AddonIfc::g_ifc->killCalled;

  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_KODI_MONITOR_ABORT_REQUESTED_V1_END>---*/
}

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_4>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_4_END>---*/
