/*
 *  Copyright (C) 2005-2021 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

/* File autogenerated, see xbmc/addons/kodi-dev-kit/tools/code-generator/code_generator.py */

/*
 * This header is used to allow direct api interface between addon and Kodi.
 * Becomes used in case the addon is loaded as dynamic lib and without use of
 * shared memory.
 *
 * This can be in case if higher performance needed or OS not support
 * independent apps (e.g. iOS/tvos)
 *
 * The structure defined here is only used between library and Kodi not used
 * inside addon itself, with this are changes here not critical.
 */

#pragma once

#include "src/shared/api/addon-instance/audiodecoder.h"
#include "src/shared/api/addon-instance/audioencoder.h"
#include "src/shared/api/addon-instance/game.h"
#include "src/shared/api/addon-instance/imagedecoder.h"
#include "src/shared/api/addon-instance/inputstream.h"
#include "src/shared/api/addon-instance/peripheral.h"
#include "src/shared/api/addon-instance/pvr.h"
#include "src/shared/api/addon-instance/screensaver.h"
#include "src/shared/api/addon-instance/vfs.h"
#include "src/shared/api/addon-instance/videocodec.h"
#include "src/shared/api/addon-instance/visualization.h"
#include "src/shared/api/addon_base.h"
#include "src/shared/api/audio_engine.h"
#include "src/shared/api/filesystem.h"
#include "src/shared/api/general.h"
#include "src/shared/api/gui/controls/button.h"
#include "src/shared/api/gui/controls/edit.h"
#include "src/shared/api/gui/controls/fade_label.h"
#include "src/shared/api/gui/controls/image.h"
#include "src/shared/api/gui/controls/label.h"
#include "src/shared/api/gui/controls/progress.h"
#include "src/shared/api/gui/controls/radio_button.h"
#include "src/shared/api/gui/controls/rendering.h"
#include "src/shared/api/gui/controls/settings_slider.h"
#include "src/shared/api/gui/controls/slider.h"
#include "src/shared/api/gui/controls/spin.h"
#include "src/shared/api/gui/controls/text_box.h"
#include "src/shared/api/gui/dialogs/context_menu.h"
#include "src/shared/api/gui/dialogs/extended_progress.h"
#include "src/shared/api/gui/dialogs/filebrowser.h"
#include "src/shared/api/gui/dialogs/keyboard.h"
#include "src/shared/api/gui/dialogs/numeric.h"
#include "src/shared/api/gui/dialogs/ok.h"
#include "src/shared/api/gui/dialogs/progress.h"
#include "src/shared/api/gui/dialogs/select.h"
#include "src/shared/api/gui/dialogs/text_viewer.h"
#include "src/shared/api/gui/dialogs/yes_no.h"
#include "src/shared/api/gui/general.h"
#include "src/shared/api/gui/list_item.h"
#include "src/shared/api/gui/window.h"
#include "src/shared/api/monitor.h"
#include "src/shared/api/network.h"
#include "src/shared/api/processor.h"

namespace KODI
{
namespace ADDONS
{
namespace INTERFACE
{

struct DirectAddonIfcToKodi
{
  directFuncToKodi_addon_base_h addon_base_h;
  directFuncToKodi_audio_engine_h audio_engine_h;
  directFuncToKodi_filesystem_h filesystem_h;
  directFuncToKodi_general_h general_h;
  directFuncToKodi_monitor_h monitor_h;
  directFuncToKodi_network_h network_h;
  directFuncToKodi_addoninstance_audiodecoder_h addoninstance_audiodecoder_h;
  directFuncToKodi_addoninstance_audioencoder_h addoninstance_audioencoder_h;
  directFuncToKodi_addoninstance_game_h addoninstance_game_h;
  directFuncToKodi_addoninstance_imagedecoder_h addoninstance_imagedecoder_h;
  directFuncToKodi_addoninstance_inputstream_h addoninstance_inputstream_h;
  directFuncToKodi_addoninstance_peripheral_h addoninstance_peripheral_h;
  directFuncToKodi_addoninstance_pvr_h addoninstance_pvr_h;
  directFuncToKodi_addoninstance_screensaver_h addoninstance_screensaver_h;
  directFuncToKodi_addoninstance_vfs_h addoninstance_vfs_h;
  directFuncToKodi_addoninstance_videocodec_h addoninstance_videocodec_h;
  directFuncToKodi_addoninstance_visualization_h addoninstance_visualization_h;
  directFuncToKodi_gui_general_h gui_general_h;
  directFuncToKodi_gui_list_item_h gui_list_item_h;
  directFuncToKodi_gui_window_h gui_window_h;
  directFuncToKodi_gui_controls_button_h gui_controls_button_h;
  directFuncToKodi_gui_controls_edit_h gui_controls_edit_h;
  directFuncToKodi_gui_controls_fade_label_h gui_controls_fade_label_h;
  directFuncToKodi_gui_controls_image_h gui_controls_image_h;
  directFuncToKodi_gui_controls_label_h gui_controls_label_h;
  directFuncToKodi_gui_controls_progress_h gui_controls_progress_h;
  directFuncToKodi_gui_controls_radio_button_h gui_controls_radio_button_h;
  directFuncToKodi_gui_controls_rendering_h gui_controls_rendering_h;
  directFuncToKodi_gui_controls_settings_slider_h gui_controls_settings_slider_h;
  directFuncToKodi_gui_controls_slider_h gui_controls_slider_h;
  directFuncToKodi_gui_controls_spin_h gui_controls_spin_h;
  directFuncToKodi_gui_controls_text_box_h gui_controls_text_box_h;
  directFuncToKodi_gui_dialogs_context_menu_h gui_dialogs_context_menu_h;
  directFuncToKodi_gui_dialogs_extended_progress_h gui_dialogs_extended_progress_h;
  directFuncToKodi_gui_dialogs_filebrowser_h gui_dialogs_filebrowser_h;
  directFuncToKodi_gui_dialogs_keyboard_h gui_dialogs_keyboard_h;
  directFuncToKodi_gui_dialogs_numeric_h gui_dialogs_numeric_h;
  directFuncToKodi_gui_dialogs_ok_h gui_dialogs_ok_h;
  directFuncToKodi_gui_dialogs_progress_h gui_dialogs_progress_h;
  directFuncToKodi_gui_dialogs_select_h gui_dialogs_select_h;
  directFuncToKodi_gui_dialogs_text_viewer_h gui_dialogs_text_viewer_h;
  directFuncToKodi_gui_dialogs_yes_no_h gui_dialogs_yes_no_h;
};

struct DirectAddonIfcToAddon
{
  directFuncToAddon_addon_base_h addon_base_h;
  directFuncToAddon_audio_engine_h audio_engine_h;
  directFuncToAddon_filesystem_h filesystem_h;
  directFuncToAddon_general_h general_h;
  directFuncToAddon_monitor_h monitor_h;
  directFuncToAddon_network_h network_h;
  directFuncToAddon_addoninstance_audiodecoder_h addoninstance_audiodecoder_h;
  directFuncToAddon_addoninstance_audioencoder_h addoninstance_audioencoder_h;
  directFuncToAddon_addoninstance_game_h addoninstance_game_h;
  directFuncToAddon_addoninstance_imagedecoder_h addoninstance_imagedecoder_h;
  directFuncToAddon_addoninstance_inputstream_h addoninstance_inputstream_h;
  directFuncToAddon_addoninstance_peripheral_h addoninstance_peripheral_h;
  directFuncToAddon_addoninstance_pvr_h addoninstance_pvr_h;
  directFuncToAddon_addoninstance_screensaver_h addoninstance_screensaver_h;
  directFuncToAddon_addoninstance_vfs_h addoninstance_vfs_h;
  directFuncToAddon_addoninstance_videocodec_h addoninstance_videocodec_h;
  directFuncToAddon_addoninstance_visualization_h addoninstance_visualization_h;
  directFuncToAddon_gui_general_h gui_general_h;
  directFuncToAddon_gui_list_item_h gui_list_item_h;
  directFuncToAddon_gui_window_h gui_window_h;
  directFuncToAddon_gui_controls_button_h gui_controls_button_h;
  directFuncToAddon_gui_controls_edit_h gui_controls_edit_h;
  directFuncToAddon_gui_controls_fade_label_h gui_controls_fade_label_h;
  directFuncToAddon_gui_controls_image_h gui_controls_image_h;
  directFuncToAddon_gui_controls_label_h gui_controls_label_h;
  directFuncToAddon_gui_controls_progress_h gui_controls_progress_h;
  directFuncToAddon_gui_controls_radio_button_h gui_controls_radio_button_h;
  directFuncToAddon_gui_controls_rendering_h gui_controls_rendering_h;
  directFuncToAddon_gui_controls_settings_slider_h gui_controls_settings_slider_h;
  directFuncToAddon_gui_controls_slider_h gui_controls_slider_h;
  directFuncToAddon_gui_controls_spin_h gui_controls_spin_h;
  directFuncToAddon_gui_controls_text_box_h gui_controls_text_box_h;
  directFuncToAddon_gui_dialogs_context_menu_h gui_dialogs_context_menu_h;
  directFuncToAddon_gui_dialogs_extended_progress_h gui_dialogs_extended_progress_h;
  directFuncToAddon_gui_dialogs_filebrowser_h gui_dialogs_filebrowser_h;
  directFuncToAddon_gui_dialogs_keyboard_h gui_dialogs_keyboard_h;
  directFuncToAddon_gui_dialogs_numeric_h gui_dialogs_numeric_h;
  directFuncToAddon_gui_dialogs_ok_h gui_dialogs_ok_h;
  directFuncToAddon_gui_dialogs_progress_h gui_dialogs_progress_h;
  directFuncToAddon_gui_dialogs_select_h gui_dialogs_select_h;
  directFuncToAddon_gui_dialogs_text_viewer_h gui_dialogs_text_viewer_h;
  directFuncToAddon_gui_dialogs_yes_no_h gui_dialogs_yes_no_h;
  directFuncToAddon_processor_h processor_h;
};

struct DirectAddonIfc
{
  DirectAddonIfcToKodi to_kodi;
  DirectAddonIfcToAddon to_addon;
};

} /* namespace INTERFACE */
} /* namespace ADDONS */
} /* namespace KODI */
