/*
 *  Copyright (C) 2005-2021 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

/* File autogenerated, see xbmc/addons/kodi-dev-kit/tools/code-generator/code_generator.py */

#pragma once

#include "addons/interface/IMsgHdl.h"

// API include
#include "addons/kodi-dev-kit/include/kodi/c-api/addon-instance/audioencoder.h"

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1_END>---*/

namespace KODI
{
namespace ADDONS
{
namespace INTERFACE
{

struct directFuncToAddon_addoninstance_audioencoder_h;
struct directFuncToKodi_addoninstance_audioencoder_h;

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2_END>---*/

class CHdl_kodi_addoninstance_audioencoder_h : public IMsgHdl
{
public:
  CHdl_kodi_addoninstance_audioencoder_h(CInterface& interface) : IMsgHdl(interface) {}

  void InitDirect(directFuncToKodi_addoninstance_audioencoder_h* ifcToKodi,
                  directFuncToAddon_addoninstance_audioencoder_h* ifcToAddon);

  // To handle callbacks from addon by shared sandbox API (static functions below in private becomes used)
  bool HandleMessage(int funcGroup,
                     int func,
                     const msgpack::unpacked& in,
                     msgpack::sbuffer& out) override;

  /* Code below becomes on auto generation reused, hand edited parts should included here */
  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_3>---*/
  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_3_END>---*/

  // Function calls from Kodi to addon
  KODI_ADDON_AUDIOENCODER_HDL kodi_addon_audioencoder_create_v1(
      KODI_OWN_HDL kodi_hdl); // Added with API 1

  void kodi_addon_audioencoder_destroy_v1(KODI_ADDON_AUDIOENCODER_HDL hdl); // Added with API 1

  bool kodi_addon_audioencoder_start_v1(
      KODI_ADDON_AUDIOENCODER_HDL hdl, const struct AUDIOENCODER_INFO_TAG* tag); // Added with API 1

  ssize_t kodi_addon_audioencoder_encode_v1(KODI_ADDON_AUDIOENCODER_HDL hdl,
                                            const uint8_t* pbt_stream,
                                            size_t num_bytes_read); // Added with API 1

  bool kodi_addon_audioencoder_finish_v1(KODI_ADDON_AUDIOENCODER_HDL hdl); // Added with API 1


private:
  /* Code below becomes on auto generation reused, hand edited parts should included here */
  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_4>---*/
  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_4_END>---*/

  // Callbacks from addon to Kodi
  static ssize_t kodi_addon_audioencoder_write_v1(void* thisClassHdl,
                                                  KODI_OWN_HDL hdl,
                                                  const uint8_t* data,
                                                  size_t len); // Added with API 1

  static ssize_t kodi_addon_audioencoder_seek_v1(void* thisClassHdl,
                                                 KODI_OWN_HDL hdl,
                                                 size_t pos,
                                                 int whence); // Added with API 1


  directFuncToAddon_addoninstance_audioencoder_h* m_ifcToAddon{nullptr};
};

} /* namespace INTERFACE */
} /* namespace ADDONS */
} /* namespace KODI */
