/*
 *  Copyright (C) 2005-2021 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

/* File autogenerated, see xbmc/addons/kodi-dev-kit/tools/code-generator/code_generator.py */

#pragma once

#include "../../../../../include/kodi/c-api/gui/dialogs/extended_progress.h"
#include "src/shared/SharedGroups.h"

#include <string.h>
#include <string>
#include <tuple>
#include <vector>

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1_END>---*/

namespace KODI
{
namespace ADDONS
{
namespace INTERFACE
{

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2_END>---*/

// Code here relates to direct API calls without use of shared mem from addon to Kodi.
//{{{

typedef KODI_GUI_HANDLE(
    ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_NEW_DIALOG_V1)(void*,
                                                                                 const char*);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_IS_FINISHED_V1)(
    void*, KODI_GUI_HANDLE);
typedef char*(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_GET_TEXT_V1)(
    void*, KODI_GUI_HANDLE);
typedef char*(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_GET_TITLE_V1)(
    void*, KODI_GUI_HANDLE);
typedef float(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_GET_PERCENTAGE_V1)(
    void*, KODI_GUI_HANDLE);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_DELETE_DIALOG_V1)(
    void*, KODI_GUI_HANDLE);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_MARK_FINISHED_V1)(
    void*, KODI_GUI_HANDLE);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_SET_PERCENTAGE_V1)(
    void*, KODI_GUI_HANDLE, float);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_SET_PROGRESS_V1)(
    void*, KODI_GUI_HANDLE, int, int);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_SET_TEXT_V1)(
    void*, KODI_GUI_HANDLE, const char*);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_SET_TITLE_V1)(
    void*, KODI_GUI_HANDLE, const char*);

struct directFuncToKodi_gui_dialogs_extended_progress_h
{
  void* thisClassHdl;
  PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_DELETE_DIALOG_V1
      kodi_gui_dialogs_extended_progress_delete_dialog_v1;
  PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_GET_PERCENTAGE_V1
      kodi_gui_dialogs_extended_progress_get_percentage_v1;
  PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_GET_TEXT_V1
      kodi_gui_dialogs_extended_progress_get_text_v1;
  PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_GET_TITLE_V1
      kodi_gui_dialogs_extended_progress_get_title_v1;
  PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_IS_FINISHED_V1
      kodi_gui_dialogs_extended_progress_is_finished_v1;
  PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_MARK_FINISHED_V1
      kodi_gui_dialogs_extended_progress_mark_finished_v1;
  PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_NEW_DIALOG_V1
      kodi_gui_dialogs_extended_progress_new_dialog_v1;
  PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_SET_PERCENTAGE_V1
      kodi_gui_dialogs_extended_progress_set_percentage_v1;
  PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_SET_PROGRESS_V1
      kodi_gui_dialogs_extended_progress_set_progress_v1;
  PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_SET_TEXT_V1
      kodi_gui_dialogs_extended_progress_set_text_v1;
  PFN_INT_KODI_GUI_DIALOGS_EXTENDED_PROGRESS_SET_TITLE_V1
      kodi_gui_dialogs_extended_progress_set_title_v1;
};

//}}}

// Code here relates to direct API calls without use of shared mem from Kodi to addon.
//{{{


struct directFuncToAddon_gui_dialogs_extended_progress_h
{
  void* thisClassHdl;
};

//}}}

typedef enum funcParent_gui_dialogs_extended_progress_h : int
{
  funcParent_kodi_gui_dialogs_extended_progress_new_dialog_v1,
  funcParent_kodi_gui_dialogs_extended_progress_delete_dialog_v1,
  funcParent_kodi_gui_dialogs_extended_progress_get_title_v1,
  funcParent_kodi_gui_dialogs_extended_progress_set_title_v1,
  funcParent_kodi_gui_dialogs_extended_progress_get_text_v1,
  funcParent_kodi_gui_dialogs_extended_progress_set_text_v1,
  funcParent_kodi_gui_dialogs_extended_progress_is_finished_v1,
  funcParent_kodi_gui_dialogs_extended_progress_mark_finished_v1,
  funcParent_kodi_gui_dialogs_extended_progress_get_percentage_v1,
  funcParent_kodi_gui_dialogs_extended_progress_set_percentage_v1,
  funcParent_kodi_gui_dialogs_extended_progress_set_progress_v1,
} funcParent_gui_dialogs_extended_progress_h;

// clang-format off
/*---AUTO_GEN_PARSE<FUNC_PARENT_TUPLES>---*/
// Original API call: ATTR_DLL_EXPORT KODI_GUI_HANDLE kodi_gui_dialogs_extended_progress_new_dialog(const char* title) __INTRODUCED_IN_KODI(1);
typedef std::tuple<std::string> msgParent__IN_kodi_gui_dialogs_extended_progress_new_dialog_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgParent_OUT_kodi_gui_dialogs_extended_progress_new_dialog_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_dialogs_extended_progress_delete_dialog(KODI_GUI_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_dialogs_extended_progress_delete_dialog_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_dialogs_extended_progress_delete_dialog_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT char* kodi_gui_dialogs_extended_progress_get_title(KODI_GUI_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_dialogs_extended_progress_get_title_v1; /* Autogenerated */
typedef std::tuple<std::string> msgParent_OUT_kodi_gui_dialogs_extended_progress_get_title_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_dialogs_extended_progress_set_title(KODI_GUI_HANDLE handle, const char* title) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string> msgParent__IN_kodi_gui_dialogs_extended_progress_set_title_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_dialogs_extended_progress_set_title_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT char* kodi_gui_dialogs_extended_progress_get_text(KODI_GUI_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_dialogs_extended_progress_get_text_v1; /* Autogenerated */
typedef std::tuple<std::string> msgParent_OUT_kodi_gui_dialogs_extended_progress_get_text_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_dialogs_extended_progress_set_text(KODI_GUI_HANDLE handle, const char* text) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string> msgParent__IN_kodi_gui_dialogs_extended_progress_set_text_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_dialogs_extended_progress_set_text_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_gui_dialogs_extended_progress_is_finished(KODI_GUI_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_dialogs_extended_progress_is_finished_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_gui_dialogs_extended_progress_is_finished_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_dialogs_extended_progress_mark_finished(KODI_GUI_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_dialogs_extended_progress_mark_finished_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_dialogs_extended_progress_mark_finished_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT float kodi_gui_dialogs_extended_progress_get_percentage(KODI_GUI_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_dialogs_extended_progress_get_percentage_v1; /* Autogenerated */
typedef std::tuple<float> msgParent_OUT_kodi_gui_dialogs_extended_progress_get_percentage_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_dialogs_extended_progress_set_percentage(KODI_GUI_HANDLE handle, float percentage) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, float> msgParent__IN_kodi_gui_dialogs_extended_progress_set_percentage_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_dialogs_extended_progress_set_percentage_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_dialogs_extended_progress_set_progress(KODI_GUI_HANDLE handle, int currentItem, int itemCount) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int, int> msgParent__IN_kodi_gui_dialogs_extended_progress_set_progress_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_dialogs_extended_progress_set_progress_v1; /* Autogenerated */
/*---AUTO_GEN_PARSE<FUNC_PARENT_TUPLES_END>---*/
// clang-format on

//==============================================================================

typedef enum funcChild_gui_dialogs_extended_progress_h : int
{
  funcChild_gui_dialogs_extended_progress_h_dummy
} funcChild_gui_dialogs_extended_progress_h;

// clang-format off
/*---AUTO_GEN_PARSE<FUNC_CHILD_TUPLES>---*/
/*---AUTO_GEN_PARSE<FUNC_CHILD_TUPLES_END>---*/
// clang-format on

} /* namespace INTERFACE */
} /* namespace ADDONS */
} /* namespace KODI */
