/*
 *  Copyright (C) 2005-2021 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

/* File autogenerated, see xbmc/addons/kodi-dev-kit/tools/code-generator/code_generator.py */

#pragma once

#include "addons/interface/IMsgHdl.h"

// API include
#include "addons/kodi-dev-kit/include/kodi/c-api/gui/general.h"

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1_END>---*/

namespace KODI
{
namespace ADDONS
{
namespace INTERFACE
{

struct directFuncToAddon_gui_general_h;
struct directFuncToKodi_gui_general_h;

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2_END>---*/

class CHdl_kodi_gui_general_h : public IMsgHdl
{
public:
  CHdl_kodi_gui_general_h(CInterface& interface) : IMsgHdl(interface) {}

  void InitDirect(directFuncToKodi_gui_general_h* ifcToKodi,
                  directFuncToAddon_gui_general_h* ifcToAddon);

  // To handle callbacks from addon by shared sandbox API (static functions below in private becomes used)
  bool HandleMessage(int funcGroup,
                     int func,
                     const msgpack::unpacked& in,
                     msgpack::sbuffer& out) override;

  /* Code below becomes on auto generation reused, hand edited parts should included here */
  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_3>---*/
  static void lock();
  static void unlock();
  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_3_END>---*/

  // Function calls from Kodi to addon

private:
  /* Code below becomes on auto generation reused, hand edited parts should included here */
  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_4>---*/
  static int m_iAddonGUILockRef;
  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_4_END>---*/

  // Callbacks from addon to Kodi
  static void kodi_gui_lock_v1(void* thisClassHdl); // Added with API 1

  static void kodi_gui_unlock_v1(void* thisClassHdl); // Added with API 1

  static int kodi_gui_get_screen_height_v1(void* thisClassHdl); // Added with API 1

  static int kodi_gui_get_screen_width_v1(void* thisClassHdl); // Added with API 1

  static float kodi_gui_get_video_resolution_v1(void* thisClassHdl); // Added with API 1

  static int kodi_gui_get_current_window_dialog_id_v1(void* thisClassHdl); // Added with API 1

  static int kodi_gui_get_current_window_id_v1(void* thisClassHdl); // Added with API 1

  static ADDON_HARDWARE_CONTEXT2 kodi_gui_get_hw_context_v1(void* thisClassHdl); // Added with API 1


  directFuncToAddon_gui_general_h* m_ifcToAddon{nullptr};
};

} /* namespace INTERFACE */
} /* namespace ADDONS */
} /* namespace KODI */
