/*
 *  Copyright (C) 2005-2021 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

/* File autogenerated, see xbmc/addons/kodi-dev-kit/tools/code-generator/code_generator.py */

#pragma once

#include "../../../../../include/kodi/c-api/gui/controls/text_box.h"
#include "src/shared/SharedGroups.h"

#include <string.h>
#include <string>
#include <tuple>
#include <vector>

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1_END>---*/

namespace KODI
{
namespace ADDONS
{
namespace INTERFACE
{

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2_END>---*/

// Code here relates to direct API calls without use of shared mem from addon to Kodi.
//{{{

typedef char*(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_CONTROLS_TEXT_BOX_GET_TEXT_V1)(
    void*, KODI_GUI_CONTROL_HANDLE);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_CONTROLS_TEXT_BOX_RESET_V1)(
    void*, KODI_GUI_CONTROL_HANDLE);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_CONTROLS_TEXT_BOX_SCROLL_V1)(
    void*, KODI_GUI_CONTROL_HANDLE, unsigned int);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_CONTROLS_TEXT_BOX_SET_AUTO_SCROLLING_V1)(
    void*, KODI_GUI_CONTROL_HANDLE, int, int, int);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_CONTROLS_TEXT_BOX_SET_TEXT_V1)(
    void*, KODI_GUI_CONTROL_HANDLE, const char*);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_CONTROLS_TEXT_BOX_SET_VISIBLE_V1)(
    void*, KODI_GUI_CONTROL_HANDLE, bool);

struct directFuncToKodi_gui_controls_text_box_h
{
  void* thisClassHdl;
  PFN_INT_KODI_GUI_CONTROLS_TEXT_BOX_GET_TEXT_V1 kodi_gui_controls_text_box_get_text_v1;
  PFN_INT_KODI_GUI_CONTROLS_TEXT_BOX_RESET_V1 kodi_gui_controls_text_box_reset_v1;
  PFN_INT_KODI_GUI_CONTROLS_TEXT_BOX_SCROLL_V1 kodi_gui_controls_text_box_scroll_v1;
  PFN_INT_KODI_GUI_CONTROLS_TEXT_BOX_SET_AUTO_SCROLLING_V1
      kodi_gui_controls_text_box_set_auto_scrolling_v1;
  PFN_INT_KODI_GUI_CONTROLS_TEXT_BOX_SET_TEXT_V1 kodi_gui_controls_text_box_set_text_v1;
  PFN_INT_KODI_GUI_CONTROLS_TEXT_BOX_SET_VISIBLE_V1 kodi_gui_controls_text_box_set_visible_v1;
};

//}}}

// Code here relates to direct API calls without use of shared mem from Kodi to addon.
//{{{


struct directFuncToAddon_gui_controls_text_box_h
{
  void* thisClassHdl;
};

//}}}

typedef enum funcParent_gui_controls_text_box_h : int
{
  funcParent_kodi_gui_controls_text_box_set_visible_v1,
  funcParent_kodi_gui_controls_text_box_reset_v1,
  funcParent_kodi_gui_controls_text_box_set_text_v1,
  funcParent_kodi_gui_controls_text_box_get_text_v1,
  funcParent_kodi_gui_controls_text_box_scroll_v1,
  funcParent_kodi_gui_controls_text_box_set_auto_scrolling_v1,
} funcParent_gui_controls_text_box_h;

// clang-format off
/*---AUTO_GEN_PARSE<FUNC_PARENT_TUPLES>---*/
// Original API call: ATTR_DLL_EXPORT void kodi_gui_controls_text_box_set_visible(KODI_GUI_CONTROL_HANDLE handle, bool visible) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, bool> msgParent__IN_kodi_gui_controls_text_box_set_visible_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_controls_text_box_set_visible_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_controls_text_box_reset(KODI_GUI_CONTROL_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_controls_text_box_reset_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_controls_text_box_reset_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_controls_text_box_set_text(KODI_GUI_CONTROL_HANDLE handle, const char* text) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string> msgParent__IN_kodi_gui_controls_text_box_set_text_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_controls_text_box_set_text_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT char* kodi_gui_controls_text_box_get_text(KODI_GUI_CONTROL_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_controls_text_box_get_text_v1; /* Autogenerated */
typedef std::tuple<std::string> msgParent_OUT_kodi_gui_controls_text_box_get_text_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_controls_text_box_scroll(KODI_GUI_CONTROL_HANDLE handle, unsigned int position) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, unsigned int> msgParent__IN_kodi_gui_controls_text_box_scroll_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_controls_text_box_scroll_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_controls_text_box_set_auto_scrolling( KODI_GUI_CONTROL_HANDLE handle, int delay, int time, int repeat) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int, int, int> msgParent__IN_kodi_gui_controls_text_box_set_auto_scrolling_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_controls_text_box_set_auto_scrolling_v1; /* Autogenerated */
/*---AUTO_GEN_PARSE<FUNC_PARENT_TUPLES_END>---*/
// clang-format on

//==============================================================================

typedef enum funcChild_gui_controls_text_box_h : int
{
  funcChild_gui_controls_text_box_h_dummy
} funcChild_gui_controls_text_box_h;

// clang-format off
/*---AUTO_GEN_PARSE<FUNC_CHILD_TUPLES>---*/
/*---AUTO_GEN_PARSE<FUNC_CHILD_TUPLES_END>---*/
// clang-format on

} /* namespace INTERFACE */
} /* namespace ADDONS */
} /* namespace KODI */
