/*
 *  Copyright (C) 2005-2021 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

/* File autogenerated, see xbmc/addons/kodi-dev-kit/tools/code-generator/code_generator.py */

#include "rendering.h"

// Shared API
#include "addons/kodi-dev-kit/src/shared/api/gui/controls/rendering.h"

// Kodi
#include "addons/interface/RunningProcess.h"
#include "utils/log.h"

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1>---*/

#include "addons/interface/api/gui/general.h"
#include "guilib/GUIRenderingControl.h"

/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1_END>---*/

namespace KODI
{
namespace ADDONS
{
namespace INTERFACE
{

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2_END>---*/

void CHdl_kodi_gui_controls_rendering_h::InitDirect(
    directFuncToKodi_gui_controls_rendering_h* ifcToKodi,
    directFuncToAddon_gui_controls_rendering_h* ifcToAddon)
{
  ifcToKodi->thisClassHdl = this;
  m_ifcToAddon = ifcToAddon;
  ifcToKodi->kodi_gui_controls_radio_rendering_destroy_v1 =
      kodi_gui_controls_radio_rendering_destroy_v1;
}

bool CHdl_kodi_gui_controls_rendering_h::HandleMessage(int funcGroup,
                                                       int func,
                                                       const msgpack::unpacked& in,
                                                       msgpack::sbuffer& out)
{
  if (funcGroup != funcGroup_gui_controls_rendering_h)
    return false;

  switch (func)
  {
    case funcParent_kodi_gui_controls_radio_rendering_destroy_v1:
    {
      // Original API call: ATTR_DLL_EXPORT void kodi_gui_controls_radio_rendering_destroy(KODI_GUI_CONTROL_HANDLE handle) __INTRODUCED_IN_KODI(1);
      // Tuple in:          typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_controls_radio_rendering_destroy_v1; /* Autogenerated */
      // Tuple out:         typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_controls_radio_rendering_destroy_v1; /* Autogenerated */
      msgParent__IN_kodi_gui_controls_radio_rendering_destroy_v1 t = in.get().as<decltype(t)>();
      KODI_GUI_CONTROL_HANDLE handle = reinterpret_cast<KODI_GUI_CONTROL_HANDLE>(std::get<0>(t));
      kodi_gui_controls_radio_rendering_destroy_v1(this, handle);
      return true;
    }
    default:
      CLog::Log(LOGERROR,
                "CHdl_kodi_gui_controls_rendering_h::{}: addon called with unknown function id "
                "'{}' on group 'gui_controls_rendering_h'",
                __func__, func);
  }

  return false;
}

// Function calls from Kodi to addon
/* NOTE: unused (no functions here) */

// Callbacks from addon to Kodi

void CHdl_kodi_gui_controls_rendering_h::kodi_gui_controls_radio_rendering_destroy_v1(
    void* thisClassHdl, KODI_GUI_CONTROL_HANDLE handle)
{
  auto thisClass = reinterpret_cast<CHdl_kodi_gui_controls_rendering_h*>(thisClassHdl);
  if (thisClass == nullptr)
    return;

  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_KODI_GUI_CONTROLS_RADIO_RENDERING_DESTROY>---*/

  CHdl_kodi_gui_general_h::lock();
  //   static_cast<CGUIAddonRenderingControl*>(handle)->Delete();
  CHdl_kodi_gui_general_h::unlock();

  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_KODI_GUI_CONTROLS_RADIO_RENDERING_DESTROY_END>---*/
}

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_3>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_3_END>---*/

} /* namespace INTERFACE */
} /* namespace ADDONS */
} /* namespace KODI */
