/*
 *  Copyright (C) 2005-2021 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

/* File autogenerated, see xbmc/addons/kodi-dev-kit/tools/code-generator/code_generator.py */

#pragma once

#include "../../../../include/kodi/c-api/gui/window.h"
#include "src/shared/SharedGroups.h"

#include <string.h>
#include <string>
#include <tuple>
#include <vector>

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1_END>---*/

namespace KODI
{
namespace ADDONS
{
namespace INTERFACE
{

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2_END>---*/

// Code here relates to direct API calls without use of shared mem from addon to Kodi.
//{{{

typedef KODI_GUI_CONTROL_HANDLE(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_BUTTON_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, int);
typedef KODI_GUI_CONTROL_HANDLE(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_EDIT_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, int);
typedef KODI_GUI_CONTROL_HANDLE(
    ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_FADE_LABEL_V1)(void*,
                                                                          KODI_GUI_WINDOW_HANDLE,
                                                                          int);
typedef KODI_GUI_CONTROL_HANDLE(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_IMAGE_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, int);
typedef KODI_GUI_CONTROL_HANDLE(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_LABEL_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, int);
typedef KODI_GUI_CONTROL_HANDLE(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_PROGRESS_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, int);
typedef KODI_GUI_CONTROL_HANDLE(
    ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_RADIO_BUTTON_V1)(void*,
                                                                            KODI_GUI_WINDOW_HANDLE,
                                                                            int);
typedef KODI_GUI_CONTROL_HANDLE(
    ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_RENDER_ADDON_V1)(void*,
                                                                            KODI_GUI_WINDOW_HANDLE,
                                                                            int);
typedef KODI_GUI_CONTROL_HANDLE(
    ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_SETTINGS_SLIDER_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, int);
typedef KODI_GUI_CONTROL_HANDLE(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_SLIDER_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, int);
typedef KODI_GUI_CONTROL_HANDLE(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_SPIN_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, int);
typedef KODI_GUI_CONTROL_HANDLE(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_TEXT_BOX_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, int);
typedef KODI_GUI_LISTITEM_HANDLE(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_LIST_ITEM_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, int);
typedef KODI_GUI_WINDOW_HANDLE(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_CREATE_V1)(
    void*, KODI_HANDLE, const char*, const char*, bool, bool);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_CLOSE_V1)(void*, KODI_GUI_WINDOW_HANDLE);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_DO_MODAL_V1)(void*, KODI_GUI_WINDOW_HANDLE);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_PROPERTY_BOOL_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, const char*);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_SET_FOCUS_ID_V1)(void*,
                                                                         KODI_GUI_WINDOW_HANDLE,
                                                                         int);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_SHOW_V1)(void*, KODI_GUI_WINDOW_HANDLE);
typedef char*(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_PROPERTY_V1)(void*,
                                                                          KODI_GUI_WINDOW_HANDLE,
                                                                          const char*);
typedef double(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_PROPERTY_DOUBLE_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, const char*);
typedef int(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_CURRENT_CONTAINER_ID_V1)(
    void*, KODI_GUI_WINDOW_HANDLE);
typedef int(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_CURRENT_LIST_POSITION_V1)(
    void*, KODI_GUI_WINDOW_HANDLE);
typedef int(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_FOCUS_ID_V1)(void*,
                                                                        KODI_GUI_WINDOW_HANDLE);
typedef int(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_LIST_SIZE_V1)(void*,
                                                                         KODI_GUI_WINDOW_HANDLE);
typedef int(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_GET_PROPERTY_INT_V1)(void*,
                                                                            KODI_GUI_WINDOW_HANDLE,
                                                                            const char*);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_ADD_LIST_ITEM_V1)(void*,
                                                                          KODI_GUI_WINDOW_HANDLE,
                                                                          KODI_GUI_LISTITEM_HANDLE,
                                                                          int);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_CLEAR_ITEM_LIST_V1)(void*,
                                                                            KODI_GUI_WINDOW_HANDLE);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_CLEAR_PROPERTIES_V1)(
    void*, KODI_GUI_WINDOW_HANDLE);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_CLEAR_PROPERTY_V1)(void*,
                                                                           KODI_GUI_WINDOW_HANDLE,
                                                                           const char*);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_DESTROY_V1)(void*, KODI_GUI_WINDOW_HANDLE);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_MARK_DIRTY_REGION_V1)(
    void*, KODI_GUI_WINDOW_HANDLE);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_REMOVE_LIST_ITEM_FROM_POSITION_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, int);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_REMOVE_LIST_ITEM_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, KODI_GUI_LISTITEM_HANDLE);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_SET_CONTAINER_CONTENT_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, const char*);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_SET_CONTAINER_PROPERTY_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, const char*, const char*);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_SET_CONTROL_LABEL_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, int, const char*);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_SET_CONTROL_SELECTED_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, int, bool);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_SET_CONTROL_VISIBLE_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, int, bool);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_SET_CURRENT_LIST_POSITION_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, int);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_SET_PROPERTY_BOOL_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, const char*, bool);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_SET_PROPERTY_DOUBLE_V1)(
    void*, KODI_GUI_WINDOW_HANDLE, const char*, double);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_SET_PROPERTY_INT_V1)(void*,
                                                                             KODI_GUI_WINDOW_HANDLE,
                                                                             const char*,
                                                                             int);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_GUI_WINDOW_SET_PROPERTY_V1)(void*,
                                                                         KODI_GUI_WINDOW_HANDLE,
                                                                         const char*,
                                                                         const char*);

struct directFuncToKodi_gui_window_h
{
  void* thisClassHdl;
  PFN_INT_KODI_GUI_WINDOW_ADD_LIST_ITEM_V1 kodi_gui_window_add_list_item_v1;
  PFN_INT_KODI_GUI_WINDOW_CLEAR_ITEM_LIST_V1 kodi_gui_window_clear_item_list_v1;
  PFN_INT_KODI_GUI_WINDOW_CLEAR_PROPERTIES_V1 kodi_gui_window_clear_properties_v1;
  PFN_INT_KODI_GUI_WINDOW_CLEAR_PROPERTY_V1 kodi_gui_window_clear_property_v1;
  PFN_INT_KODI_GUI_WINDOW_CLOSE_V1 kodi_gui_window_close_v1;
  PFN_INT_KODI_GUI_WINDOW_CREATE_V1 kodi_gui_window_create_v1;
  PFN_INT_KODI_GUI_WINDOW_DESTROY_V1 kodi_gui_window_destroy_v1;
  PFN_INT_KODI_GUI_WINDOW_DO_MODAL_V1 kodi_gui_window_do_modal_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_BUTTON_V1 kodi_gui_window_get_control_button_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_EDIT_V1 kodi_gui_window_get_control_edit_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_FADE_LABEL_V1 kodi_gui_window_get_control_fade_label_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_IMAGE_V1 kodi_gui_window_get_control_image_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_LABEL_V1 kodi_gui_window_get_control_label_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_PROGRESS_V1 kodi_gui_window_get_control_progress_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_RADIO_BUTTON_V1 kodi_gui_window_get_control_radio_button_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_RENDER_ADDON_V1 kodi_gui_window_get_control_render_addon_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_SETTINGS_SLIDER_V1
      kodi_gui_window_get_control_settings_slider_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_SLIDER_V1 kodi_gui_window_get_control_slider_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_SPIN_V1 kodi_gui_window_get_control_spin_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_CONTROL_TEXT_BOX_V1 kodi_gui_window_get_control_text_box_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_CURRENT_CONTAINER_ID_V1 kodi_gui_window_get_current_container_id_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_CURRENT_LIST_POSITION_V1 kodi_gui_window_get_current_list_position_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_FOCUS_ID_V1 kodi_gui_window_get_focus_id_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_LIST_ITEM_V1 kodi_gui_window_get_list_item_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_LIST_SIZE_V1 kodi_gui_window_get_list_size_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_PROPERTY_BOOL_V1 kodi_gui_window_get_property_bool_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_PROPERTY_DOUBLE_V1 kodi_gui_window_get_property_double_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_PROPERTY_INT_V1 kodi_gui_window_get_property_int_v1;
  PFN_INT_KODI_GUI_WINDOW_GET_PROPERTY_V1 kodi_gui_window_get_property_v1;
  PFN_INT_KODI_GUI_WINDOW_MARK_DIRTY_REGION_V1 kodi_gui_window_mark_dirty_region_v1;
  PFN_INT_KODI_GUI_WINDOW_REMOVE_LIST_ITEM_FROM_POSITION_V1
      kodi_gui_window_remove_list_item_from_position_v1;
  PFN_INT_KODI_GUI_WINDOW_REMOVE_LIST_ITEM_V1 kodi_gui_window_remove_list_item_v1;
  PFN_INT_KODI_GUI_WINDOW_SET_CONTAINER_CONTENT_V1 kodi_gui_window_set_container_content_v1;
  PFN_INT_KODI_GUI_WINDOW_SET_CONTAINER_PROPERTY_V1 kodi_gui_window_set_container_property_v1;
  PFN_INT_KODI_GUI_WINDOW_SET_CONTROL_LABEL_V1 kodi_gui_window_set_control_label_v1;
  PFN_INT_KODI_GUI_WINDOW_SET_CONTROL_SELECTED_V1 kodi_gui_window_set_control_selected_v1;
  PFN_INT_KODI_GUI_WINDOW_SET_CONTROL_VISIBLE_V1 kodi_gui_window_set_control_visible_v1;
  PFN_INT_KODI_GUI_WINDOW_SET_CURRENT_LIST_POSITION_V1 kodi_gui_window_set_current_list_position_v1;
  PFN_INT_KODI_GUI_WINDOW_SET_FOCUS_ID_V1 kodi_gui_window_set_focus_id_v1;
  PFN_INT_KODI_GUI_WINDOW_SET_PROPERTY_BOOL_V1 kodi_gui_window_set_property_bool_v1;
  PFN_INT_KODI_GUI_WINDOW_SET_PROPERTY_DOUBLE_V1 kodi_gui_window_set_property_double_v1;
  PFN_INT_KODI_GUI_WINDOW_SET_PROPERTY_INT_V1 kodi_gui_window_set_property_int_v1;
  PFN_INT_KODI_GUI_WINDOW_SET_PROPERTY_V1 kodi_gui_window_set_property_v1;
  PFN_INT_KODI_GUI_WINDOW_SHOW_V1 kodi_gui_window_show_v1;
};

//}}}

// Code here relates to direct API calls without use of shared mem from Kodi to addon.
//{{{


struct directFuncToAddon_gui_window_h
{
  void* thisClassHdl;
};

//}}}

typedef enum funcParent_gui_window_h : int
{
  funcParent_kodi_gui_window_create_v1,
  funcParent_kodi_gui_window_destroy_v1,
  funcParent_kodi_gui_window_show_v1,
  funcParent_kodi_gui_window_close_v1,
  funcParent_kodi_gui_window_do_modal_v1,
  funcParent_kodi_gui_window_set_focus_id_v1,
  funcParent_kodi_gui_window_get_focus_id_v1,
  funcParent_kodi_gui_window_set_control_label_v1,
  funcParent_kodi_gui_window_set_control_visible_v1,
  funcParent_kodi_gui_window_set_control_selected_v1,
  funcParent_kodi_gui_window_set_property_v1,
  funcParent_kodi_gui_window_set_property_int_v1,
  funcParent_kodi_gui_window_set_property_bool_v1,
  funcParent_kodi_gui_window_set_property_double_v1,
  funcParent_kodi_gui_window_get_property_v1,
  funcParent_kodi_gui_window_get_property_int_v1,
  funcParent_kodi_gui_window_get_property_bool_v1,
  funcParent_kodi_gui_window_get_property_double_v1,
  funcParent_kodi_gui_window_clear_properties_v1,
  funcParent_kodi_gui_window_clear_property_v1,
  funcParent_kodi_gui_window_clear_item_list_v1,
  funcParent_kodi_gui_window_add_list_item_v1,
  funcParent_kodi_gui_window_remove_list_item_from_position_v1,
  funcParent_kodi_gui_window_remove_list_item_v1,
  funcParent_kodi_gui_window_get_list_item_v1,
  funcParent_kodi_gui_window_set_current_list_position_v1,
  funcParent_kodi_gui_window_get_current_list_position_v1,
  funcParent_kodi_gui_window_get_list_size_v1,
  funcParent_kodi_gui_window_set_container_property_v1,
  funcParent_kodi_gui_window_set_container_content_v1,
  funcParent_kodi_gui_window_get_current_container_id_v1,
  funcParent_kodi_gui_window_mark_dirty_region_v1,
  funcParent_kodi_gui_window_get_control_button_v1,
  funcParent_kodi_gui_window_get_control_edit_v1,
  funcParent_kodi_gui_window_get_control_fade_label_v1,
  funcParent_kodi_gui_window_get_control_image_v1,
  funcParent_kodi_gui_window_get_control_label_v1,
  funcParent_kodi_gui_window_get_control_progress_v1,
  funcParent_kodi_gui_window_get_control_radio_button_v1,
  funcParent_kodi_gui_window_get_control_render_addon_v1,
  funcParent_kodi_gui_window_get_control_settings_slider_v1,
  funcParent_kodi_gui_window_get_control_slider_v1,
  funcParent_kodi_gui_window_get_control_spin_v1,
  funcParent_kodi_gui_window_get_control_text_box_v1,
} funcParent_gui_window_h;

// clang-format off
/*---AUTO_GEN_PARSE<FUNC_PARENT_TUPLES>---*/
// Original API call: ATTR_DLL_EXPORT KODI_GUI_WINDOW_HANDLE kodi_gui_window_create(KODI_HANDLE kodiBase, const char* xml_filename, const char* default_skin, bool as_dialog, bool is_media) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string, std::string, bool, bool> msgParent__IN_kodi_gui_window_create_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgParent_OUT_kodi_gui_window_create_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_destroy(KODI_GUI_WINDOW_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_window_destroy_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_destroy_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_gui_window_show(KODI_GUI_WINDOW_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_window_show_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_gui_window_show_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_gui_window_close(KODI_GUI_WINDOW_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_window_close_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_gui_window_close_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_gui_window_do_modal(KODI_GUI_WINDOW_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_window_do_modal_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_gui_window_do_modal_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_gui_window_set_focus_id(KODI_GUI_WINDOW_HANDLE handle, int control_id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_set_focus_id_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_gui_window_set_focus_id_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT int kodi_gui_window_get_focus_id(KODI_GUI_WINDOW_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_window_get_focus_id_v1; /* Autogenerated */
typedef std::tuple<int> msgParent_OUT_kodi_gui_window_get_focus_id_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_set_control_label(KODI_GUI_WINDOW_HANDLE handle, int control_id, const char* label) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int, std::string> msgParent__IN_kodi_gui_window_set_control_label_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_set_control_label_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_set_control_visible(KODI_GUI_WINDOW_HANDLE handle, int control_id, bool visible) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int, bool> msgParent__IN_kodi_gui_window_set_control_visible_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_set_control_visible_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_set_control_selected(KODI_GUI_WINDOW_HANDLE handle, int control_id, bool selected) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int, bool> msgParent__IN_kodi_gui_window_set_control_selected_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_set_control_selected_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_set_property(KODI_GUI_WINDOW_HANDLE handle, const char* key, const char* value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string, std::string> msgParent__IN_kodi_gui_window_set_property_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_set_property_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_set_property_int(KODI_GUI_WINDOW_HANDLE handle, const char* key, int value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string, int> msgParent__IN_kodi_gui_window_set_property_int_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_set_property_int_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_set_property_bool(KODI_GUI_WINDOW_HANDLE handle, const char* key, bool value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string, bool> msgParent__IN_kodi_gui_window_set_property_bool_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_set_property_bool_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_set_property_double(KODI_GUI_WINDOW_HANDLE handle, const char* key, double value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string, double> msgParent__IN_kodi_gui_window_set_property_double_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_set_property_double_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT char* kodi_gui_window_get_property(KODI_GUI_WINDOW_HANDLE handle, const char* key) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string> msgParent__IN_kodi_gui_window_get_property_v1; /* Autogenerated */
typedef std::tuple<std::string> msgParent_OUT_kodi_gui_window_get_property_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT int kodi_gui_window_get_property_int(KODI_GUI_WINDOW_HANDLE handle, const char* key) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string> msgParent__IN_kodi_gui_window_get_property_int_v1; /* Autogenerated */
typedef std::tuple<int> msgParent_OUT_kodi_gui_window_get_property_int_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_gui_window_get_property_bool(KODI_GUI_WINDOW_HANDLE handle, const char* key) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string> msgParent__IN_kodi_gui_window_get_property_bool_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_gui_window_get_property_bool_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT double kodi_gui_window_get_property_double(KODI_GUI_WINDOW_HANDLE handle, const char* key) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string> msgParent__IN_kodi_gui_window_get_property_double_v1; /* Autogenerated */
typedef std::tuple<double> msgParent_OUT_kodi_gui_window_get_property_double_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_clear_properties(KODI_GUI_WINDOW_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_window_clear_properties_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_clear_properties_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_clear_property(KODI_GUI_WINDOW_HANDLE handle, const char* key) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string> msgParent__IN_kodi_gui_window_clear_property_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_clear_property_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_clear_item_list(KODI_GUI_WINDOW_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_window_clear_item_list_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_clear_item_list_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_add_list_item(KODI_GUI_WINDOW_HANDLE handle, KODI_GUI_LISTITEM_HANDLE item, int list_position) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, PtrValue, int> msgParent__IN_kodi_gui_window_add_list_item_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_add_list_item_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_remove_list_item_from_position(KODI_GUI_WINDOW_HANDLE handle, int list_position) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_remove_list_item_from_position_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_remove_list_item_from_position_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_remove_list_item(KODI_GUI_WINDOW_HANDLE handle, KODI_GUI_LISTITEM_HANDLE item) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, PtrValue> msgParent__IN_kodi_gui_window_remove_list_item_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_remove_list_item_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT KODI_GUI_LISTITEM_HANDLE kodi_gui_window_get_list_item(KODI_GUI_WINDOW_HANDLE handle, int list_position) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_get_list_item_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgParent_OUT_kodi_gui_window_get_list_item_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_set_current_list_position(KODI_GUI_WINDOW_HANDLE handle, int list_position) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_set_current_list_position_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_set_current_list_position_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT int kodi_gui_window_get_current_list_position(KODI_GUI_WINDOW_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_window_get_current_list_position_v1; /* Autogenerated */
typedef std::tuple<int> msgParent_OUT_kodi_gui_window_get_current_list_position_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT int kodi_gui_window_get_list_size(KODI_GUI_WINDOW_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_window_get_list_size_v1; /* Autogenerated */
typedef std::tuple<int> msgParent_OUT_kodi_gui_window_get_list_size_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_set_container_property(KODI_GUI_WINDOW_HANDLE handle, const char* key, const char* value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string, std::string> msgParent__IN_kodi_gui_window_set_container_property_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_set_container_property_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_set_container_content(KODI_GUI_WINDOW_HANDLE handle, const char* value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string> msgParent__IN_kodi_gui_window_set_container_content_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_set_container_content_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT int kodi_gui_window_get_current_container_id(KODI_GUI_WINDOW_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_window_get_current_container_id_v1; /* Autogenerated */
typedef std::tuple<int> msgParent_OUT_kodi_gui_window_get_current_container_id_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT void kodi_gui_window_mark_dirty_region(KODI_GUI_WINDOW_HANDLE handle) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_gui_window_mark_dirty_region_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_gui_window_mark_dirty_region_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT KODI_GUI_CONTROL_HANDLE kodi_gui_window_get_control_button( KODI_GUI_WINDOW_HANDLE handle, int control_id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_get_control_button_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgParent_OUT_kodi_gui_window_get_control_button_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT KODI_GUI_CONTROL_HANDLE kodi_gui_window_get_control_edit( KODI_GUI_WINDOW_HANDLE handle, int control_id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_get_control_edit_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgParent_OUT_kodi_gui_window_get_control_edit_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT KODI_GUI_CONTROL_HANDLE kodi_gui_window_get_control_fade_label( KODI_GUI_WINDOW_HANDLE handle, int control_id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_get_control_fade_label_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgParent_OUT_kodi_gui_window_get_control_fade_label_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT KODI_GUI_CONTROL_HANDLE kodi_gui_window_get_control_image( KODI_GUI_WINDOW_HANDLE handle, int control_id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_get_control_image_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgParent_OUT_kodi_gui_window_get_control_image_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT KODI_GUI_CONTROL_HANDLE kodi_gui_window_get_control_label( KODI_GUI_WINDOW_HANDLE handle, int control_id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_get_control_label_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgParent_OUT_kodi_gui_window_get_control_label_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT KODI_GUI_CONTROL_HANDLE kodi_gui_window_get_control_progress( KODI_GUI_WINDOW_HANDLE handle, int control_id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_get_control_progress_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgParent_OUT_kodi_gui_window_get_control_progress_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT KODI_GUI_CONTROL_HANDLE kodi_gui_window_get_control_radio_button( KODI_GUI_WINDOW_HANDLE handle, int control_id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_get_control_radio_button_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgParent_OUT_kodi_gui_window_get_control_radio_button_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT KODI_GUI_CONTROL_HANDLE kodi_gui_window_get_control_render_addon( KODI_GUI_WINDOW_HANDLE handle, int control_id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_get_control_render_addon_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgParent_OUT_kodi_gui_window_get_control_render_addon_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT KODI_GUI_CONTROL_HANDLE kodi_gui_window_get_control_settings_slider( KODI_GUI_WINDOW_HANDLE handle, int control_id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_get_control_settings_slider_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgParent_OUT_kodi_gui_window_get_control_settings_slider_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT KODI_GUI_CONTROL_HANDLE kodi_gui_window_get_control_slider( KODI_GUI_WINDOW_HANDLE handle, int control_id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_get_control_slider_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgParent_OUT_kodi_gui_window_get_control_slider_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT KODI_GUI_CONTROL_HANDLE kodi_gui_window_get_control_spin( KODI_GUI_WINDOW_HANDLE handle, int control_id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_get_control_spin_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgParent_OUT_kodi_gui_window_get_control_spin_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT KODI_GUI_CONTROL_HANDLE kodi_gui_window_get_control_text_box( KODI_GUI_WINDOW_HANDLE handle, int control_id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, int> msgParent__IN_kodi_gui_window_get_control_text_box_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgParent_OUT_kodi_gui_window_get_control_text_box_v1; /* Autogenerated */
/*---AUTO_GEN_PARSE<FUNC_PARENT_TUPLES_END>---*/
// clang-format on

//==============================================================================

typedef enum funcChild_gui_window_h : int
{
  funcChild_gui_window_h_dummy
} funcChild_gui_window_h;

// clang-format off
/*---AUTO_GEN_PARSE<FUNC_CHILD_TUPLES>---*/
/*---AUTO_GEN_PARSE<FUNC_CHILD_TUPLES_END>---*/
// clang-format on

} /* namespace INTERFACE */
} /* namespace ADDONS */
} /* namespace KODI */
